name: CrediMax - Build & Push Trainer

on:
  push:
    branches: [ main ]

jobs:
  build-trainer:
    runs-on: ubuntu-latest

    permissions:
      packages: write
      contents: read

    steps:
      - uses: actions/checkout@v3

      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: deepactionpotential
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Trainer image
        run: |
          docker build -t ghcr.io/deepactionpotential/crediMax-trainer:latest \
            -f docker/trainer.Dockerfile .

      - name: Push Trainer Image
        run: docker push ghcr.io/deepactionpotential/credimax-trainer:latest
